<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: fch
 * Date: Fri, 30 Apr 2010 11:35:18 +0200
 */

$conf['title'] = 'Devsnotebook\'s wiki';
$conf['lang'] = 'fr';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
