<?php
// Français translation of SyntaxeHl, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:68
$GLOBALS['__l10n']['SyntaxeHl configuration']='Configuration de SyntaxeHl';

# _admin.php:73
$GLOBALS['__l10n']['Overall CSS class :']='Class CSS commune :';

# _admin.php:76
$GLOBALS['__l10n']['Leave empty to cancel this feature.']='Laissez vide pour annuler ce comportement';

# _admin.php:83
$GLOBALS['__l10n']['Enable keyword link']='Activer les liens sur les mots clés';

# _admin.php:87
$GLOBALS['__l10n']['Enable line numbers']='Activer la numérotation des lignes';

?>