<?php
// French translation of SyntaxeHl, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:67
$GLOBALS['__l10n']['SyntaxeHl configuration']='Configuration de SyntaxeHl';

# _admin.php:72
$GLOBALS['__l10n']['Overall CSS class :']='Class CSS commune :';

# _admin.php:82
$GLOBALS['__l10n']['Enable keyword link']='Activer les liens sur les mots clés';

# _admin.php:86
$GLOBALS['__l10n']['Enable line numbers']='Activer la numérotation des lignes';

?>